### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by DonutsNL** [DonutsNL/glpisaml#3]
Implement Access-Control-Allow-Origin: https://idp.domain header for CORS enabled environments.

**Comment by jhouxatjvx** [comment]
Can you explain what this feature would do?
I thought adding Access-Control-Allow-Origin header is something done by webserver (apache/nginx)

**Comment by DonutsNL** [comment]
The general idea is to extract the domain information from the idp url config and generate the CORS header using this information.

**Comment by jhouxatjvx** [comment]
Ok I think I see.  So it has the same effect as if you had manually configured the apache server to respond with CORS headers for requests that came from the IDP Domain.  But having PHP figure it out automatically from the plugin configuration saves you from having to configure apache.  Is this correct?

**Comment by DonutsNL** [comment]
It is, it also prevents configuration mistakes and typo's and allows us to validate the urls and check if they are valid.
