### ISSUE TITLE
Logo for plugin

### ISSUE THREAD

**Issue by DonutsNL** [DonutsNL/glpisaml#4]
I am looking for help, can someone design a cool looking logo for the plugin to be shown in the plugin page and in the GLPI marketplace?

![image](https://github.com/DonutsNL/phpsaml2/assets/97617761/6c7c1f4c-df66-48a2-886d-ce262022a035)

**Comment by SpyK-01** [comment]
Hello,

Do you have any Discord or something to discuss with you?

Regards Spyk

**Comment by DonutsNL** [comment]
I have, the link is somewhere in the readme. If i find a moment ill be online in aprix 2 hours from now

**Comment by DonutsNL** [comment]
https://discord.gg/kMZXyPsB
